#data
data_folder: ../data/processed_data
data_name: octmnist_processed.pt
is_image: true

#loss
beta: 2 # (dapres l'article beta = 2.0 pour diabetes apres le grid search)


#training
batch_size: 64
num_classes : 4
lr : 0.01
weight_decay: 0.00001 #1e-5
num_epochs: 20

num_epochs_recNet : 5
lr_recNet : 0.001 

#sauvegarde
model_save_folder: ../models
model_save_name: model_octminst

#logname
log_folder: ../logs
log_name: octmnist
